# These functions were generated by the {beekeeper} package, based on
# components@security_schemes from the source API description. You may want to
# delete unused options. In addition, APIs often have additional security
# options that are not formally documented in the API description. For example,
# for any `location = query` `api_key` options, it might be possible to instead
# pass the same parameter in a header, possibly with a different name. Consult
# the text description of authentication in your API documentation.

# An API key provided by the API provider. This key is not clearly documented in the API description. Check the API documentation for details.
cu_security_apikey_auth <- function(req, cu_api_key) {
  nectar::security_api_key(
    req,
    location = "header",
    parameter_name = "Authorization",
    api_key = cu_api_key
  )
}
